-- ============================================
-- Questions and Answers Schema for Oracle Database
-- ============================================

-- Create Sequences
CREATE SEQUENCE QUESTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ANSWER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE QUESTION_VOTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ANSWER_VOTE_SEQ START WITH 1 INCREMENT BY 1;

-- Create QUESTIONS table
CREATE TABLE QUESTIONS (
    QUESTION_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(500) NOT NULL,
    CONTENT CLOB NOT NULL,
    TAGS VARCHAR2(500),
    VIEWS NUMBER(10) DEFAULT 0,
    VOTES NUMBER(10) DEFAULT 0,
    ANSWER_COUNT NUMBER(10) DEFAULT 0,
    IS_ANSWERED NUMBER(1) DEFAULT 0,
    ACCEPTED_ANSWER_ID NUMBER(19),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_QUESTIONS_USER FOREIGN KEY (USER_ID) 
        REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_IS_ANSWERED CHECK (IS_ANSWERED IN (0, 1))
);

-- Create ANSWERS table
CREATE TABLE ANSWERS (
    ANSWER_ID NUMBER(19) PRIMARY KEY,
    QUESTION_ID NUMBER(19) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    CONTENT CLOB NOT NULL,
    VOTES NUMBER(10) DEFAULT 0,
    IS_ACCEPTED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ANSWERS_QUESTION FOREIGN KEY (QUESTION_ID) 
        REFERENCES QUESTIONS(QUESTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ANSWERS_USER FOREIGN KEY (USER_ID) 
        REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_IS_ACCEPTED CHECK (IS_ACCEPTED IN (0, 1))
);

-- Create QUESTION_VOTES table (track user votes on questions)
CREATE TABLE QUESTION_VOTES (
    VOTE_ID NUMBER(19) PRIMARY KEY,
    QUESTION_ID NUMBER(19) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    VOTE_TYPE NUMBER(2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_QVOTE_QUESTION FOREIGN KEY (QUESTION_ID) 
        REFERENCES QUESTIONS(QUESTION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_QVOTE_USER FOREIGN KEY (USER_ID) 
        REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_QVOTE_TYPE CHECK (VOTE_TYPE IN (-1, 1)),
    CONSTRAINT UQ_QUESTION_USER_VOTE UNIQUE (QUESTION_ID, USER_ID)
);

-- Create ANSWER_VOTES table (track user votes on answers)
CREATE TABLE ANSWER_VOTES (
    VOTE_ID NUMBER(19) PRIMARY KEY,
    ANSWER_ID NUMBER(19) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    VOTE_TYPE NUMBER(2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_AVOTE_ANSWER FOREIGN KEY (ANSWER_ID) 
        REFERENCES ANSWERS(ANSWER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_AVOTE_USER FOREIGN KEY (USER_ID) 
        REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_AVOTE_TYPE CHECK (VOTE_TYPE IN (-1, 1)),
    CONSTRAINT UQ_ANSWER_USER_VOTE UNIQUE (ANSWER_ID, USER_ID)
);

-- Create indexes for better performance
CREATE INDEX IDX_QUESTIONS_USER_ID ON QUESTIONS(USER_ID);
CREATE INDEX IDX_QUESTIONS_CREATED_AT ON QUESTIONS(CREATED_AT DESC);
CREATE INDEX IDX_QUESTIONS_VOTES ON QUESTIONS(VOTES DESC);
CREATE INDEX IDX_QUESTIONS_VIEWS ON QUESTIONS(VIEWS DESC);
CREATE INDEX IDX_ANSWERS_QUESTION_ID ON ANSWERS(QUESTION_ID);
CREATE INDEX IDX_ANSWERS_USER_ID ON ANSWERS(USER_ID);
CREATE INDEX IDX_ANSWERS_CREATED_AT ON ANSWERS(CREATED_AT DESC);
CREATE INDEX IDX_QVOTES_QUESTION_ID ON QUESTION_VOTES(QUESTION_ID);
CREATE INDEX IDX_AVOTES_ANSWER_ID ON ANSWER_VOTES(ANSWER_ID);

-- Create trigger to update UPDATED_AT on questions
CREATE OR REPLACE TRIGGER TRG_QUESTIONS_UPDATE
BEFORE UPDATE ON QUESTIONS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Create trigger to update UPDATED_AT on answers
CREATE OR REPLACE TRIGGER TRG_ANSWERS_UPDATE
BEFORE UPDATE ON ANSWERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

-- Create trigger to update answer count when answer is added
CREATE OR REPLACE TRIGGER TRG_ANSWER_COUNT_INSERT
AFTER INSERT ON ANSWERS
FOR EACH ROW
BEGIN
    UPDATE QUESTIONS 
    SET ANSWER_COUNT = ANSWER_COUNT + 1
    WHERE QUESTION_ID = :NEW.QUESTION_ID;
END;
/

-- Create trigger to update answer count when answer is deleted
CREATE OR REPLACE TRIGGER TRG_ANSWER_COUNT_DELETE
AFTER DELETE ON ANSWERS
FOR EACH ROW
BEGIN
    UPDATE QUESTIONS 
    SET ANSWER_COUNT = ANSWER_COUNT - 1
    WHERE QUESTION_ID = :OLD.QUESTION_ID;
END;
/

-- Comments for documentation
COMMENT ON TABLE QUESTIONS IS 'Stores user questions';
COMMENT ON TABLE ANSWERS IS 'Stores answers to questions';
COMMENT ON TABLE QUESTION_VOTES IS 'Stores upvotes/downvotes on questions';
COMMENT ON TABLE ANSWER_VOTES IS 'Stores upvotes/downvotes on answers';

COMMIT;

PROMPT
PROMPT ============================================
PROMPT Questions and Answers tables created successfully!
PROMPT ============================================
