-- Oracle Database Schema for User Profile Dashboard

-- Create Sequences
CREATE SEQUENCE USER_PROFILE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USER_POST_SEQ START WITH 1 INCREMENT BY 1;

-- Create USER_PROFILE table
CREATE TABLE USER_PROFILE (
    USER_ID NUMBER(19) PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(50),
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    LOCATION VARCHAR2(100),
    WEBSITE VARCHAR2(200),
    BIO VARCHAR2(500),
    PROFILE_IMAGE VARCHAR2(500),
    COVER_IMAGE VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create USER_STATS table
CREATE TABLE USER_STATS (
    USER_ID NUMBER(19) PRIMARY KEY,
    POSTS NUMBER(10) DEFAULT 0 NOT NULL,
    FOLLOWERS NUMBER(10) DEFAULT 0 NOT NULL,
    FOLLOWING NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_USER_STATS_PROFILE FOREIGN KEY (USER_ID) 
        REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE
);

-- Create USER_POSTS table
CREATE TABLE USER_POSTS (
    POST_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    POST_TYPE VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_USER_POSTS_PROFILE FOREIGN KEY (USER_ID) 
        REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_POST_TYPE CHECK (POST_TYPE IN ('TEXT', 'IMAGE', 'VIDEO', 'ARTICLE'))
);

-- Create indexes for better performance
CREATE INDEX IDX_USER_PROFILE_EMAIL ON USER_PROFILE(EMAIL);
CREATE INDEX IDX_USER_POSTS_USER_ID ON USER_POSTS(USER_ID);
CREATE INDEX IDX_USER_POSTS_CREATED_AT ON USER_POSTS(CREATED_AT DESC);

-- Comments for documentation
COMMENT ON TABLE USER_PROFILE IS 'Stores user profile information';
COMMENT ON TABLE USER_STATS IS 'Stores user statistics (posts, followers, following)';
COMMENT ON TABLE USER_POSTS IS 'Stores user posts and content';
